import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  headerWrapper: {
    width: '100%',
    alignItems: 'center',
    marginLeft: 15,
    marginBottom: 10,
  },
  headerImage: {
    width: width * 0.95,
    height: height * 0.25,
  },
  titleContainer: {
    width: '90%',
    alignItems: 'center',
    marginBottom: 25,
  },
  menuTitle: {
    fontSize: 24,
    color: '#fffde1',
    fontWeight: '700',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  menu: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 25,
  },
  card: {
    width: width * 0.4,
    height: width * 0.4,
    backgroundColor: '#f78219',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#f78219',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  cardSpacer: {
    width: 20,
  },
  cardLabel: {
    color: '#fffde1',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 10,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  bottomCardContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 25,
  },
  bottomCard: {
    width: '90%',
    height: 80,
    backgroundColor: '#f78219',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    shadowColor: '#f78219',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  bottomCardLabel: {
    color: '#fffde1',
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 15,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  logout: {
    position: 'absolute',
    bottom: height * 0.05,
    width: '90%',
    backgroundColor: '#f78219',
    paddingVertical: 15,
    borderRadius: 25,
    alignItems: 'center',
    shadowColor: '#f78219',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  logoutText: {
    color: '#fffde1',
    fontSize: 18,
    fontWeight: '700',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});
