import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  background: { flex: 1 },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  backButton: {
    position: 'absolute',
    top: height * 0.08,
    left: 30,
    zIndex: 10,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    width: width * 0.9,
    height: 50,
    backgroundColor: '#f78219',
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#f78219',
    marginBottom: 20,
    justifyContent: 'center',
    shadowColor: '#f78219',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  selectText: {
    color: '#fffde1',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 10,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    width: width * 0.9,
    height: 50,
    backgroundColor: '#f78219',
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#f78219',
    marginVertical: 10,
    justifyContent: 'center',
    shadowColor: '#f78219',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  actionText: {
    color: '#fffde1',
    fontSize: 16,
    marginLeft: 10,
    fontWeight: '600',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modal: {
    width: '80%',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 15,
    textAlign: 'center',
  },
  examItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  examName: {
    fontSize: 16,
    color: '#333',
  },
  closeModal: {
    marginTop: 20,
    paddingVertical: 12,
    backgroundColor: '#f78219',
    borderRadius: 12,
    alignItems: 'center',
  },
  closeText: {
    color: '#fffde1',
    fontSize: 16,
    fontWeight: '600',
  },
});
