import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 15,
    backgroundColor: '#f5f6fa',
  },
  contentContainer: {
    paddingBottom: 15,
  },
  section: {
    marginBottom: 15,
    backgroundColor: '#ffffff',
    borderRadius: 6,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  inputGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    backgroundColor: '#ffffff',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  icon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    fontSize: 14,
    color: '#333333',
    paddingVertical: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 10,
  },
  calendarContainer: {
    borderRadius: 6,
    overflow: 'hidden',
    marginTop: 6,
  },
  selectedDateText: {
    marginTop: 10,
    fontSize: 13,
    color: '#666666',
    textAlign: 'center',
  },
  buttonContainer: {
    marginTop: 15,
    marginBottom: 15,
  },
  button: {
    flexDirection: 'row',
    marginTop: -10,
    alignItems: 'center',
    height: 50,
    backgroundColor: '#f78219',
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#f78219',
    justifyContent: 'center',
  },
  printButton: {
    width: '100%',
    height: 45,
    borderRadius: 22,
    backgroundColor: '#61af58',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  menuButton: {
    width: '100%',
    height: 45,
    borderRadius: 22,
    backgroundColor: '#f78219',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '600',
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 8,
    marginBottom: 8,
  },
  headerMonth: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333333',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    backgroundColor: '#f0f0f0',
    borderRadius: 6,
    marginBottom: 15,
  },
  addButtonText: {
    color: '#f78219',
    marginLeft: 8,
    fontWeight: '600',
  },
  questionItem: {
    backgroundColor: '#f9f9f9',
    padding: 12,
    borderRadius: 6,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  questionText: {
    fontSize: 14,
    color: '#333',
    marginBottom: 5,
    fontWeight: '500',
  },
  optionText: {
    fontSize: 13,
    color: '#555',
    marginLeft: 10,
    marginBottom: 3,
  },
  correctAnswer: {
    fontSize: 13,
    color: '#4CAF50',
    fontWeight: '600',
    marginTop: 5,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    width: '90%',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  questionInput: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 6,
    padding: 10,
    marginBottom: 15,
    fontSize: 14,
  },
  optionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  optionLetter: {
    width: 24,
    fontSize: 14,
    fontWeight: 'bold',
  },
  optionInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 6,
    padding: 8,
    marginRight: 10,
    fontSize: 14,
  },
  radioButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ccc',
  },
  radioButtonSelected: {
    backgroundColor: '#f78219',
    borderColor: '#f78219',
  },
  saveQuestionButton: {
    backgroundColor: '#f78219',
    padding: 12,
    borderRadius: 6,
    alignItems: 'center',
    marginTop: 10,
  },
  saveQuestionText: {
    color: 'white',
    fontWeight: '600',
  },
});

export default styles;
